### ISSUE TITLE
[JOSS review] - Statement of Need

### ISSUE THREAD

**Issue by strengejacke** [bernadette-eu/Bernadette#11]
Related to this submission: https://github.com/openjournals/joss-reviews/issues/5612

I think the readme also requires a short statement of need section, which seems to be missing. You can use the section from the paper as template, I'd say.

**Comment by bernadette-eu** [comment]
I have added a couple of paragraphs from the _Summary_ and _Statement of need_ sections to the Overview section of the README file. Thanks!
