### ISSUE TITLE
[JOSS Review] News File

### ISSUE THREAD

**Issue by rowlandseymour** [bernadette-eu/Bernadette#4]
https://github.com/bernadette-eu/Bernadette/blob/52fd51ca4468d33584926755907f56fcd90a89e3/NEWS.md?plain=1#L1

The news file should contain something, you already have `cran-comments.md` which can be easily converted. 

https://github.com/openjournals/joss-reviews/issues/5612

**Comment by bernadette-eu** [comment]
Thank you! I have modified the NEWS.md file, following `cran-comments.md`. See [here](https://github.com/bernadette-eu/Bernadette/blob/joss_review/NEWS.md).
