### ISSUE TITLE
[JOSS Review] Code of Conduct

### ISSUE THREAD

**Issue by rowlandseymour** [bernadette-eu/Bernadette#5]
https://github.com/bernadette-eu/Bernadette/blob/52fd51ca4468d33584926755907f56fcd90a89e3/CODE_OF_CONDUCT.md?plain=1#L1

Nice to see, but is it linked to anywhere or just accessed from the directory list? Maybe you could link to from the contribution guidelines. 

https://github.com/openjournals/joss-reviews/issues/5612

**Comment by bernadette-eu** [comment]
I have created a branch for the joss review. 

For this issue, I have added a "Code of Conduct" section in the [README](https://github.com/bernadette-eu/Bernadette/blob/joss_review/README.md) file, linking to the [CODE_OF_CONDUCT](https://github.com/bernadette-eu/Bernadette/blob/master/CODE_OF_CONDUCT.md).
