### ISSUE TITLE
[JOSS Review] Default prior values

### ISSUE THREAD

**Issue by rowlandseymour** [bernadette-eu/Bernadette#6]
https://github.com/bernadette-eu/Bernadette/blob/52fd51ca4468d33584926755907f56fcd90a89e3/R/priors.R#L173

Should the default values be shown in the help comments as well as in the code?

[openjournals/joss-reviews/](https://github.com/openjournals/joss-reviews/issues/5612)

**Comment by bernadette-eu** [comment]
I have improved the `description` field of the help file for priors.R and stated what the default values are in the help comments of the function `handle_prior`. Note that `handle_prior` is not an exported object, therefore the default values are presented in the `description` field.
