### ISSUE TITLE
[JOSS Review] Paper

### ISSUE THREAD

**Issue by rowlandseymour** [bernadette-eu/Bernadette#7]
https://github.com/bernadette-eu/Bernadette/blob/52fd51ca4468d33584926755907f56fcd90a89e3/paper/paper.md?plain=1#L28

This is a good paper for the JOSS journal I think. My only concern is the first sentence of the summary. It makes is sound like this is just for Covid-19, but as far as I can see, it could be for a much wider range of infectious diseases. Might it be worth being a bit broader here?

https://github.com/openjournals/joss-reviews/issues/5612

**Comment by bernadette-eu** [comment]
Thank you for your support.

The package is one of the deliverables of a [Marie Curie Action](https://cordis.europa.eu/project/id/101027218) which aimed at the development of novel statistical methodology for the modeling of infectious diseases like COVID-19. While the Bayesian hierarchical model was indeed implemented to COVID-19, your are correct to say that the package is applicable to a wider range of infectious diseases and provides a template for the end-user.

I have modified the Summary section accordingly.

**Comment by rowlandseymour** [comment]
Excellent, thanks.
