### ISSUE TITLE
[JOSS Review] Global Variable

### ISSUE THREAD

**Issue by rowlandseymour** [bernadette-eu/Bernadette#8]
https://github.com/bernadette-eu/Bernadette/blob/52fd51ca4468d33584926755907f56fcd90a89e3/R/globals.R#L1

You might want to add a comment here in case a user isn't familiar with Global Variables or is doing something that conflicts with these names. 

https://github.com/openjournals/joss-reviews/issues/5612

**Comment by bernadette-eu** [comment]
I have added a comment at the top of the [globals.R](https://github.com/bernadette-eu/Bernadette/blob/joss_review/R/globals.R) to address this.

Thanks!

**Comment by rowlandseymour** [comment]
Thanks @bernadette-eu, that's helpful.
